title: Rosetta Intro Bootcamp
description: A course for getting started in biomolecular modeling and design
theme: just-the-docs

url: https://Ashley-Vater.github.io/Rosetta-Intro-Bootcamp

aux_links:
  Template Repository: https://github.com/Ashley-Vater/Rosetta-Intro-Bootcamp
